name: 'GitHub Workflow Stats'
description: 'Get GitHub Workflow Stats'
author: 'unstableunicorn'
inputs:
  token:
    required: true
    description: 'github token: default {{ github.token }}'
    default: ${{ github.token }}
  workflows:
    required: true
    description: 'Enter workflow name or "all" to get all workflows, can use regex patterns'
    default: 'all'
  jobs:
    required: false
    description: 'Enter job name or "all" to get all jobs from workflow, can use regex patterns'
    default: 'all'
runs:
  using: 'node19'
  main: 'dist/index.js'
